%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(riak_yokozuna_pb).
-define(riak_yokozuna_pb, true).

-define(riak_yokozuna_pb_gpb_version, "3.26.4").

-ifndef('RPBYOKOZUNASCHEMAGETREQ_PB_H').
-define('RPBYOKOZUNASCHEMAGETREQ_PB_H', true).
-record(rpbyokozunaschemagetreq,
        {name                   :: binary()         % = 1
        }).
-endif.

-ifndef('RPBYOKOZUNASCHEMA_PB_H').
-define('RPBYOKOZUNASCHEMA_PB_H', true).
-record(rpbyokozunaschema,
        {name                   :: binary(),        % = 1
         content                :: binary() | undefined % = 2
        }).
-endif.

-ifndef('RPBYOKOZUNASCHEMAPUTREQ_PB_H').
-define('RPBYOKOZUNASCHEMAPUTREQ_PB_H', true).
-record(rpbyokozunaschemaputreq,
        {schema                 :: #rpbyokozunaschema{} % = 1
        }).
-endif.

-ifndef('RPBYOKOZUNASCHEMAGETRESP_PB_H').
-define('RPBYOKOZUNASCHEMAGETRESP_PB_H', true).
-record(rpbyokozunaschemagetresp,
        {schema                 :: #rpbyokozunaschema{} % = 1
        }).
-endif.

-ifndef('RPBYOKOZUNAINDEX_PB_H').
-define('RPBYOKOZUNAINDEX_PB_H', true).
-record(rpbyokozunaindex,
        {name                   :: binary(),        % = 1
         schema                 :: binary() | undefined, % = 2
         n_val                  :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('RPBYOKOZUNAINDEXPUTREQ_PB_H').
-define('RPBYOKOZUNAINDEXPUTREQ_PB_H', true).
-record(rpbyokozunaindexputreq,
        {index                  :: #rpbyokozunaindex{}, % = 1
         timeout                :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('RPBYOKOZUNAINDEXGETREQ_PB_H').
-define('RPBYOKOZUNAINDEXGETREQ_PB_H', true).
-record(rpbyokozunaindexgetreq,
        {name                   :: binary() | undefined % = 1
        }).
-endif.

-ifndef('RPBYOKOZUNAINDEXDELETEREQ_PB_H').
-define('RPBYOKOZUNAINDEXDELETEREQ_PB_H', true).
-record(rpbyokozunaindexdeletereq,
        {name                   :: binary()         % = 1
        }).
-endif.

-ifndef('RPBYOKOZUNAINDEXGETRESP_PB_H').
-define('RPBYOKOZUNAINDEXGETRESP_PB_H', true).
-record(rpbyokozunaindexgetresp,
        {index = []             :: [#rpbyokozunaindex{}] % = 1
        }).
-endif.

-endif.
