%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4
-module(riak_yokozuna_pb).

-export([encode_msg/1, encode_msg/2]).
-export([encode/1]). %% epb compatibility
-export([encode_rpbyokozunaschemagetreq/1]).
-export([encode_rpbyokozunaschema/1]).
-export([encode_rpbyokozunaschemaputreq/1]).
-export([encode_rpbyokozunaschemagetresp/1]).
-export([encode_rpbyokozunaindex/1]).
-export([encode_rpbyokozunaindexputreq/1]).
-export([encode_rpbyokozunaindexgetreq/1]).
-export([encode_rpbyokozunaindexdeletereq/1]).
-export([encode_rpbyokozunaindexgetresp/1]).

-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3]).
-export([decode/2]). %% epb compatibility
-export([decode_rpbyokozunaschemagetreq/1]).
-export([decode_rpbyokozunaschema/1]).
-export([decode_rpbyokozunaschemaputreq/1]).
-export([decode_rpbyokozunaschemagetresp/1]).
-export([decode_rpbyokozunaindex/1]).
-export([decode_rpbyokozunaindexputreq/1]).
-export([decode_rpbyokozunaindexgetreq/1]).
-export([decode_rpbyokozunaindexdeletereq/1]).
-export([decode_rpbyokozunaindexgetresp/1]).

-export([verify_msg/1, verify_msg/2]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([get_package_name/0]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).

-include("riak_yokozuna_pb.hrl").

%% enumerated types

-export_type([]).

%% message types
-type rpbyokozunaschemagetreq() :: #rpbyokozunaschemagetreq{}.
-type rpbyokozunaschema() :: #rpbyokozunaschema{}.
-type rpbyokozunaschemaputreq() :: #rpbyokozunaschemaputreq{}.
-type rpbyokozunaschemagetresp() :: #rpbyokozunaschemagetresp{}.
-type rpbyokozunaindex() :: #rpbyokozunaindex{}.
-type rpbyokozunaindexputreq() :: #rpbyokozunaindexputreq{}.
-type rpbyokozunaindexgetreq() :: #rpbyokozunaindexgetreq{}.
-type rpbyokozunaindexdeletereq() :: #rpbyokozunaindexdeletereq{}.
-type rpbyokozunaindexgetresp() :: #rpbyokozunaindexgetresp{}.
-export_type(['rpbyokozunaschemagetreq'/0, 'rpbyokozunaschema'/0, 'rpbyokozunaschemaputreq'/0, 'rpbyokozunaschemagetresp'/0, 'rpbyokozunaindex'/0, 'rpbyokozunaindexputreq'/0, 'rpbyokozunaindexgetreq'/0, 'rpbyokozunaindexdeletereq'/0, 'rpbyokozunaindexgetresp'/0]).


-spec encode_msg(_) -> binary().
encode_msg(Msg) -> encode_msg(Msg, []).


-spec encode_msg(_, list()) -> binary().
encode_msg(Msg, Opts) ->
    case proplists:get_bool(verify, Opts) of
      true -> verify_msg(Msg, Opts);
      false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case Msg of
      #rpbyokozunaschemagetreq{} ->
	  e_msg_rpbyokozunaschemagetreq(Msg, TrUserData);
      #rpbyokozunaschema{} ->
	  e_msg_rpbyokozunaschema(Msg, TrUserData);
      #rpbyokozunaschemaputreq{} ->
	  e_msg_rpbyokozunaschemaputreq(Msg, TrUserData);
      #rpbyokozunaschemagetresp{} ->
	  e_msg_rpbyokozunaschemagetresp(Msg, TrUserData);
      #rpbyokozunaindex{} ->
	  e_msg_rpbyokozunaindex(Msg, TrUserData);
      #rpbyokozunaindexputreq{} ->
	  e_msg_rpbyokozunaindexputreq(Msg, TrUserData);
      #rpbyokozunaindexgetreq{} ->
	  e_msg_rpbyokozunaindexgetreq(Msg, TrUserData);
      #rpbyokozunaindexdeletereq{} ->
	  e_msg_rpbyokozunaindexdeletereq(Msg, TrUserData);
      #rpbyokozunaindexgetresp{} ->
	  e_msg_rpbyokozunaindexgetresp(Msg, TrUserData)
    end.


%% epb compatibility
-spec encode(_) -> binary().
encode(Msg) -> encode_msg(Msg).

-spec encode_rpbyokozunaschemagetreq(_) -> binary().
encode_rpbyokozunaschemagetreq(Msg) -> encode_msg(Msg).

-spec encode_rpbyokozunaschema(_) -> binary().
encode_rpbyokozunaschema(Msg) -> encode_msg(Msg).

-spec encode_rpbyokozunaschemaputreq(_) -> binary().
encode_rpbyokozunaschemaputreq(Msg) -> encode_msg(Msg).

-spec encode_rpbyokozunaschemagetresp(_) -> binary().
encode_rpbyokozunaschemagetresp(Msg) -> encode_msg(Msg).

-spec encode_rpbyokozunaindex(_) -> binary().
encode_rpbyokozunaindex(Msg) -> encode_msg(Msg).

-spec encode_rpbyokozunaindexputreq(_) -> binary().
encode_rpbyokozunaindexputreq(Msg) -> encode_msg(Msg).

-spec encode_rpbyokozunaindexgetreq(_) -> binary().
encode_rpbyokozunaindexgetreq(Msg) -> encode_msg(Msg).

-spec encode_rpbyokozunaindexdeletereq(_) -> binary().
encode_rpbyokozunaindexdeletereq(Msg) ->
    encode_msg(Msg).

-spec encode_rpbyokozunaindexgetresp(_) -> binary().
encode_rpbyokozunaindexgetresp(Msg) -> encode_msg(Msg).


e_msg_rpbyokozunaschemagetreq(Msg, TrUserData) ->
    e_msg_rpbyokozunaschemagetreq(Msg, <<>>, TrUserData).


e_msg_rpbyokozunaschemagetreq(#rpbyokozunaschemagetreq{name
							   = F1},
			      Bin, TrUserData) ->
    begin
      TrF1 = id(F1, TrUserData),
      e_type_bytes(TrF1, <<Bin/binary, 10>>)
    end.

e_msg_rpbyokozunaschema(Msg, TrUserData) ->
    e_msg_rpbyokozunaschema(Msg, <<>>, TrUserData).


e_msg_rpbyokozunaschema(#rpbyokozunaschema{name = F1,
					   content = F2},
			Bin, TrUserData) ->
    B1 = begin
	   TrF1 = id(F1, TrUserData),
	   e_type_bytes(TrF1, <<Bin/binary, 10>>)
	 end,
    if F2 == undefined -> B1;
       true ->
	   begin
	     TrF2 = id(F2, TrUserData),
	     e_type_bytes(TrF2, <<B1/binary, 18>>)
	   end
    end.

e_msg_rpbyokozunaschemaputreq(Msg, TrUserData) ->
    e_msg_rpbyokozunaschemaputreq(Msg, <<>>, TrUserData).


e_msg_rpbyokozunaschemaputreq(#rpbyokozunaschemaputreq{schema
							   = F1},
			      Bin, TrUserData) ->
    begin
      TrF1 = id(F1, TrUserData),
      e_mfield_rpbyokozunaschemaputreq_schema(TrF1,
					      <<Bin/binary, 10>>, TrUserData)
    end.

e_msg_rpbyokozunaschemagetresp(Msg, TrUserData) ->
    e_msg_rpbyokozunaschemagetresp(Msg, <<>>, TrUserData).


e_msg_rpbyokozunaschemagetresp(#rpbyokozunaschemagetresp{schema
							     = F1},
			       Bin, TrUserData) ->
    begin
      TrF1 = id(F1, TrUserData),
      e_mfield_rpbyokozunaschemagetresp_schema(TrF1,
					       <<Bin/binary, 10>>, TrUserData)
    end.

e_msg_rpbyokozunaindex(Msg, TrUserData) ->
    e_msg_rpbyokozunaindex(Msg, <<>>, TrUserData).


e_msg_rpbyokozunaindex(#rpbyokozunaindex{name = F1,
					 schema = F2, n_val = F3},
		       Bin, TrUserData) ->
    B1 = begin
	   TrF1 = id(F1, TrUserData),
	   e_type_bytes(TrF1, <<Bin/binary, 10>>)
	 end,
    B2 = if F2 == undefined -> B1;
	    true ->
		begin
		  TrF2 = id(F2, TrUserData),
		  e_type_bytes(TrF2, <<B1/binary, 18>>)
		end
	 end,
    if F3 == undefined -> B2;
       true ->
	   begin
	     TrF3 = id(F3, TrUserData),
	     e_varint(TrF3, <<B2/binary, 24>>)
	   end
    end.

e_msg_rpbyokozunaindexputreq(Msg, TrUserData) ->
    e_msg_rpbyokozunaindexputreq(Msg, <<>>, TrUserData).


e_msg_rpbyokozunaindexputreq(#rpbyokozunaindexputreq{index
							 = F1,
						     timeout = F2},
			     Bin, TrUserData) ->
    B1 = begin
	   TrF1 = id(F1, TrUserData),
	   e_mfield_rpbyokozunaindexputreq_index(TrF1,
						 <<Bin/binary, 10>>, TrUserData)
	 end,
    if F2 == undefined -> B1;
       true ->
	   begin
	     TrF2 = id(F2, TrUserData),
	     e_varint(TrF2, <<B1/binary, 16>>)
	   end
    end.

e_msg_rpbyokozunaindexgetreq(Msg, TrUserData) ->
    e_msg_rpbyokozunaindexgetreq(Msg, <<>>, TrUserData).


e_msg_rpbyokozunaindexgetreq(#rpbyokozunaindexgetreq{name
							 = F1},
			     Bin, TrUserData) ->
    if F1 == undefined -> Bin;
       true ->
	   begin
	     TrF1 = id(F1, TrUserData),
	     e_type_bytes(TrF1, <<Bin/binary, 10>>)
	   end
    end.

e_msg_rpbyokozunaindexdeletereq(Msg, TrUserData) ->
    e_msg_rpbyokozunaindexdeletereq(Msg, <<>>, TrUserData).


e_msg_rpbyokozunaindexdeletereq(#rpbyokozunaindexdeletereq{name
							       = F1},
				Bin, TrUserData) ->
    begin
      TrF1 = id(F1, TrUserData),
      e_type_bytes(TrF1, <<Bin/binary, 10>>)
    end.

e_msg_rpbyokozunaindexgetresp(Msg, TrUserData) ->
    e_msg_rpbyokozunaindexgetresp(Msg, <<>>, TrUserData).


e_msg_rpbyokozunaindexgetresp(#rpbyokozunaindexgetresp{index
							   = F1},
			      Bin, TrUserData) ->
    begin
      TrF1 = id(F1, TrUserData),
      if TrF1 == [] -> Bin;
	 true ->
	     e_field_rpbyokozunaindexgetresp_index(TrF1, Bin,
						   TrUserData)
      end
    end.

e_mfield_rpbyokozunaschemaputreq_schema(Msg, Bin,
					TrUserData) ->
    SubBin = e_msg_rpbyokozunaschema(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_mfield_rpbyokozunaschemagetresp_schema(Msg, Bin,
					 TrUserData) ->
    SubBin = e_msg_rpbyokozunaschema(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_mfield_rpbyokozunaindexputreq_index(Msg, Bin,
				      TrUserData) ->
    SubBin = e_msg_rpbyokozunaindex(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_mfield_rpbyokozunaindexgetresp_index(Msg, Bin,
				       TrUserData) ->
    SubBin = e_msg_rpbyokozunaindex(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_rpbyokozunaindexgetresp_index([Elem | Rest],
				      Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = e_mfield_rpbyokozunaindexgetresp_index(id(Elem,
						     TrUserData),
						  Bin2, TrUserData),
    e_field_rpbyokozunaindexgetresp_index(Rest, Bin3,
					  TrUserData);
e_field_rpbyokozunaindexgetresp_index([], Bin,
				      _TrUserData) ->
    Bin.



e_type_bytes(Bytes, Bin) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).



decode_msg(Bin, MsgName) when is_binary(Bin) ->
    decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      rpbyokozunaschemagetreq ->
	  d_msg_rpbyokozunaschemagetreq(Bin, TrUserData);
      rpbyokozunaschema ->
	  d_msg_rpbyokozunaschema(Bin, TrUserData);
      rpbyokozunaschemaputreq ->
	  d_msg_rpbyokozunaschemaputreq(Bin, TrUserData);
      rpbyokozunaschemagetresp ->
	  d_msg_rpbyokozunaschemagetresp(Bin, TrUserData);
      rpbyokozunaindex ->
	  d_msg_rpbyokozunaindex(Bin, TrUserData);
      rpbyokozunaindexputreq ->
	  d_msg_rpbyokozunaindexputreq(Bin, TrUserData);
      rpbyokozunaindexgetreq ->
	  d_msg_rpbyokozunaindexgetreq(Bin, TrUserData);
      rpbyokozunaindexdeletereq ->
	  d_msg_rpbyokozunaindexdeletereq(Bin, TrUserData);
      rpbyokozunaindexgetresp ->
	  d_msg_rpbyokozunaindexgetresp(Bin, TrUserData)
    end.


%% epb compatibility
decode(MsgName, Bin)
    when is_atom(MsgName), is_binary(Bin) ->
    decode_msg(Bin, MsgName).

decode_rpbyokozunaschemagetreq(Bin)
    when is_binary(Bin) ->
    decode_msg(Bin, rpbyokozunaschemagetreq).

decode_rpbyokozunaschema(Bin) when is_binary(Bin) ->
    decode_msg(Bin, rpbyokozunaschema).

decode_rpbyokozunaschemaputreq(Bin)
    when is_binary(Bin) ->
    decode_msg(Bin, rpbyokozunaschemaputreq).

decode_rpbyokozunaschemagetresp(Bin)
    when is_binary(Bin) ->
    decode_msg(Bin, rpbyokozunaschemagetresp).

decode_rpbyokozunaindex(Bin) when is_binary(Bin) ->
    decode_msg(Bin, rpbyokozunaindex).

decode_rpbyokozunaindexputreq(Bin)
    when is_binary(Bin) ->
    decode_msg(Bin, rpbyokozunaindexputreq).

decode_rpbyokozunaindexgetreq(Bin)
    when is_binary(Bin) ->
    decode_msg(Bin, rpbyokozunaindexgetreq).

decode_rpbyokozunaindexdeletereq(Bin)
    when is_binary(Bin) ->
    decode_msg(Bin, rpbyokozunaindexdeletereq).

decode_rpbyokozunaindexgetresp(Bin)
    when is_binary(Bin) ->
    decode_msg(Bin, rpbyokozunaindexgetresp).



d_msg_rpbyokozunaschemagetreq(Bin, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschemagetreq(Bin, 0, 0,
					       id(undefined, TrUserData),
					       TrUserData).

dfp_read_field_def_rpbyokozunaschemagetreq(<<10,
					     Rest/binary>>,
					   Z1, Z2, F1, TrUserData) ->
    d_field_rpbyokozunaschemagetreq_name(Rest, Z1, Z2, F1,
					 TrUserData);
dfp_read_field_def_rpbyokozunaschemagetreq(<<>>, 0, 0,
					   F1, _) ->
    #rpbyokozunaschemagetreq{name = F1};
dfp_read_field_def_rpbyokozunaschemagetreq(Other, Z1,
					   Z2, F1, TrUserData) ->
    dg_read_field_def_rpbyokozunaschemagetreq(Other, Z1, Z2,
					      F1, TrUserData).

dg_read_field_def_rpbyokozunaschemagetreq(<<1:1, X:7,
					    Rest/binary>>,
					  N, Acc, F1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_rpbyokozunaschemagetreq(Rest, N + 7,
					      X bsl N + Acc, F1, TrUserData);
dg_read_field_def_rpbyokozunaschemagetreq(<<0:1, X:7,
					    Rest/binary>>,
					  N, Acc, F1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_rpbyokozunaschemagetreq_name(Rest, 0, 0, F1,
					       TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_rpbyokozunaschemagetreq(Rest, 0, 0, F1,
						    TrUserData);
	    1 ->
		skip_64_rpbyokozunaschemagetreq(Rest, 0, 0, F1,
						TrUserData);
	    2 ->
		skip_length_delimited_rpbyokozunaschemagetreq(Rest, 0,
							      0, F1,
							      TrUserData);
	    5 ->
		skip_32_rpbyokozunaschemagetreq(Rest, 0, 0, F1,
						TrUserData)
	  end
    end;
dg_read_field_def_rpbyokozunaschemagetreq(<<>>, 0, 0,
					  F1, _) ->
    #rpbyokozunaschemagetreq{name = F1}.

d_field_rpbyokozunaschemagetreq_name(<<1:1, X:7,
				       Rest/binary>>,
				     N, Acc, F1, TrUserData)
    when N < 57 ->
    d_field_rpbyokozunaschemagetreq_name(Rest, N + 7,
					 X bsl N + Acc, F1, TrUserData);
d_field_rpbyokozunaschemagetreq_name(<<0:1, X:7,
				       Rest/binary>>,
				     N, Acc, _, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_rpbyokozunaschemagetreq(Rest2, 0, 0,
					       NewFValue, TrUserData).


skip_varint_rpbyokozunaschemagetreq(<<1:1, _:7,
				      Rest/binary>>,
				    Z1, Z2, F1, TrUserData) ->
    skip_varint_rpbyokozunaschemagetreq(Rest, Z1, Z2, F1,
					TrUserData);
skip_varint_rpbyokozunaschemagetreq(<<0:1, _:7,
				      Rest/binary>>,
				    Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschemagetreq(Rest, Z1, Z2,
					       F1, TrUserData).


skip_length_delimited_rpbyokozunaschemagetreq(<<1:1,
						X:7, Rest/binary>>,
					      N, Acc, F1, TrUserData)
    when N < 57 ->
    skip_length_delimited_rpbyokozunaschemagetreq(Rest,
						  N + 7, X bsl N + Acc, F1,
						  TrUserData);
skip_length_delimited_rpbyokozunaschemagetreq(<<0:1,
						X:7, Rest/binary>>,
					      N, Acc, F1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_rpbyokozunaschemagetreq(Rest2, 0, 0,
					       F1, TrUserData).


skip_32_rpbyokozunaschemagetreq(<<_:32, Rest/binary>>,
				Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschemagetreq(Rest, Z1, Z2,
					       F1, TrUserData).


skip_64_rpbyokozunaschemagetreq(<<_:64, Rest/binary>>,
				Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschemagetreq(Rest, Z1, Z2,
					       F1, TrUserData).


d_msg_rpbyokozunaschema(Bin, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschema(Bin, 0, 0,
					 id(undefined, TrUserData),
					 id(undefined, TrUserData), TrUserData).

dfp_read_field_def_rpbyokozunaschema(<<10,
				       Rest/binary>>,
				     Z1, Z2, F1, F2, TrUserData) ->
    d_field_rpbyokozunaschema_name(Rest, Z1, Z2, F1, F2,
				   TrUserData);
dfp_read_field_def_rpbyokozunaschema(<<18,
				       Rest/binary>>,
				     Z1, Z2, F1, F2, TrUserData) ->
    d_field_rpbyokozunaschema_content(Rest, Z1, Z2, F1, F2,
				      TrUserData);
dfp_read_field_def_rpbyokozunaschema(<<>>, 0, 0, F1, F2,
				     _) ->
    #rpbyokozunaschema{name = F1, content = F2};
dfp_read_field_def_rpbyokozunaschema(Other, Z1, Z2, F1,
				     F2, TrUserData) ->
    dg_read_field_def_rpbyokozunaschema(Other, Z1, Z2, F1,
					F2, TrUserData).

dg_read_field_def_rpbyokozunaschema(<<1:1, X:7,
				      Rest/binary>>,
				    N, Acc, F1, F2, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_rpbyokozunaschema(Rest, N + 7,
					X bsl N + Acc, F1, F2, TrUserData);
dg_read_field_def_rpbyokozunaschema(<<0:1, X:7,
				      Rest/binary>>,
				    N, Acc, F1, F2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_rpbyokozunaschema_name(Rest, 0, 0, F1, F2,
					 TrUserData);
      18 ->
	  d_field_rpbyokozunaschema_content(Rest, 0, 0, F1, F2,
					    TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_rpbyokozunaschema(Rest, 0, 0, F1, F2,
					      TrUserData);
	    1 ->
		skip_64_rpbyokozunaschema(Rest, 0, 0, F1, F2,
					  TrUserData);
	    2 ->
		skip_length_delimited_rpbyokozunaschema(Rest, 0, 0, F1,
							F2, TrUserData);
	    5 ->
		skip_32_rpbyokozunaschema(Rest, 0, 0, F1, F2,
					  TrUserData)
	  end
    end;
dg_read_field_def_rpbyokozunaschema(<<>>, 0, 0, F1, F2,
				    _) ->
    #rpbyokozunaschema{name = F1, content = F2}.

d_field_rpbyokozunaschema_name(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F1, F2, TrUserData)
    when N < 57 ->
    d_field_rpbyokozunaschema_name(Rest, N + 7,
				   X bsl N + Acc, F1, F2, TrUserData);
d_field_rpbyokozunaschema_name(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, _, F2, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_rpbyokozunaschema(Rest2, 0, 0,
					 NewFValue, F2, TrUserData).


d_field_rpbyokozunaschema_content(<<1:1, X:7,
				    Rest/binary>>,
				  N, Acc, F1, F2, TrUserData)
    when N < 57 ->
    d_field_rpbyokozunaschema_content(Rest, N + 7,
				      X bsl N + Acc, F1, F2, TrUserData);
d_field_rpbyokozunaschema_content(<<0:1, X:7,
				    Rest/binary>>,
				  N, Acc, F1, _, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_rpbyokozunaschema(Rest2, 0, 0, F1,
					 NewFValue, TrUserData).


skip_varint_rpbyokozunaschema(<<1:1, _:7, Rest/binary>>,
			      Z1, Z2, F1, F2, TrUserData) ->
    skip_varint_rpbyokozunaschema(Rest, Z1, Z2, F1, F2,
				  TrUserData);
skip_varint_rpbyokozunaschema(<<0:1, _:7, Rest/binary>>,
			      Z1, Z2, F1, F2, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschema(Rest, Z1, Z2, F1,
					 F2, TrUserData).


skip_length_delimited_rpbyokozunaschema(<<1:1, X:7,
					  Rest/binary>>,
					N, Acc, F1, F2, TrUserData)
    when N < 57 ->
    skip_length_delimited_rpbyokozunaschema(Rest, N + 7,
					    X bsl N + Acc, F1, F2, TrUserData);
skip_length_delimited_rpbyokozunaschema(<<0:1, X:7,
					  Rest/binary>>,
					N, Acc, F1, F2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_rpbyokozunaschema(Rest2, 0, 0, F1,
					 F2, TrUserData).


skip_32_rpbyokozunaschema(<<_:32, Rest/binary>>, Z1, Z2,
			  F1, F2, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschema(Rest, Z1, Z2, F1,
					 F2, TrUserData).


skip_64_rpbyokozunaschema(<<_:64, Rest/binary>>, Z1, Z2,
			  F1, F2, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschema(Rest, Z1, Z2, F1,
					 F2, TrUserData).


d_msg_rpbyokozunaschemaputreq(Bin, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschemaputreq(Bin, 0, 0,
					       id(undefined, TrUserData),
					       TrUserData).

dfp_read_field_def_rpbyokozunaschemaputreq(<<10,
					     Rest/binary>>,
					   Z1, Z2, F1, TrUserData) ->
    d_field_rpbyokozunaschemaputreq_schema(Rest, Z1, Z2, F1,
					   TrUserData);
dfp_read_field_def_rpbyokozunaschemaputreq(<<>>, 0, 0,
					   F1, _) ->
    #rpbyokozunaschemaputreq{schema = F1};
dfp_read_field_def_rpbyokozunaschemaputreq(Other, Z1,
					   Z2, F1, TrUserData) ->
    dg_read_field_def_rpbyokozunaschemaputreq(Other, Z1, Z2,
					      F1, TrUserData).

dg_read_field_def_rpbyokozunaschemaputreq(<<1:1, X:7,
					    Rest/binary>>,
					  N, Acc, F1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_rpbyokozunaschemaputreq(Rest, N + 7,
					      X bsl N + Acc, F1, TrUserData);
dg_read_field_def_rpbyokozunaschemaputreq(<<0:1, X:7,
					    Rest/binary>>,
					  N, Acc, F1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_rpbyokozunaschemaputreq_schema(Rest, 0, 0, F1,
						 TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_rpbyokozunaschemaputreq(Rest, 0, 0, F1,
						    TrUserData);
	    1 ->
		skip_64_rpbyokozunaschemaputreq(Rest, 0, 0, F1,
						TrUserData);
	    2 ->
		skip_length_delimited_rpbyokozunaschemaputreq(Rest, 0,
							      0, F1,
							      TrUserData);
	    5 ->
		skip_32_rpbyokozunaschemaputreq(Rest, 0, 0, F1,
						TrUserData)
	  end
    end;
dg_read_field_def_rpbyokozunaschemaputreq(<<>>, 0, 0,
					  F1, _) ->
    #rpbyokozunaschemaputreq{schema = F1}.

d_field_rpbyokozunaschemaputreq_schema(<<1:1, X:7,
					 Rest/binary>>,
				       N, Acc, F1, TrUserData)
    when N < 57 ->
    d_field_rpbyokozunaschemaputreq_schema(Rest, N + 7,
					   X bsl N + Acc, F1, TrUserData);
d_field_rpbyokozunaschemaputreq_schema(<<0:1, X:7,
					 Rest/binary>>,
				       N, Acc, F1, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bs:Len/binary, Rest2/binary>> = Rest,
    NewFValue = id(d_msg_rpbyokozunaschema(Bs, TrUserData),
		   TrUserData),
    dfp_read_field_def_rpbyokozunaschemaputreq(Rest2, 0, 0,
					       if F1 == undefined -> NewFValue;
						  true ->
						      merge_msg_rpbyokozunaschema(F1,
										  NewFValue,
										  TrUserData)
					       end,
					       TrUserData).


skip_varint_rpbyokozunaschemaputreq(<<1:1, _:7,
				      Rest/binary>>,
				    Z1, Z2, F1, TrUserData) ->
    skip_varint_rpbyokozunaschemaputreq(Rest, Z1, Z2, F1,
					TrUserData);
skip_varint_rpbyokozunaschemaputreq(<<0:1, _:7,
				      Rest/binary>>,
				    Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschemaputreq(Rest, Z1, Z2,
					       F1, TrUserData).


skip_length_delimited_rpbyokozunaschemaputreq(<<1:1,
						X:7, Rest/binary>>,
					      N, Acc, F1, TrUserData)
    when N < 57 ->
    skip_length_delimited_rpbyokozunaschemaputreq(Rest,
						  N + 7, X bsl N + Acc, F1,
						  TrUserData);
skip_length_delimited_rpbyokozunaschemaputreq(<<0:1,
						X:7, Rest/binary>>,
					      N, Acc, F1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_rpbyokozunaschemaputreq(Rest2, 0, 0,
					       F1, TrUserData).


skip_32_rpbyokozunaschemaputreq(<<_:32, Rest/binary>>,
				Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschemaputreq(Rest, Z1, Z2,
					       F1, TrUserData).


skip_64_rpbyokozunaschemaputreq(<<_:64, Rest/binary>>,
				Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschemaputreq(Rest, Z1, Z2,
					       F1, TrUserData).


d_msg_rpbyokozunaschemagetresp(Bin, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschemagetresp(Bin, 0, 0,
						id(undefined, TrUserData),
						TrUserData).

dfp_read_field_def_rpbyokozunaschemagetresp(<<10,
					      Rest/binary>>,
					    Z1, Z2, F1, TrUserData) ->
    d_field_rpbyokozunaschemagetresp_schema(Rest, Z1, Z2,
					    F1, TrUserData);
dfp_read_field_def_rpbyokozunaschemagetresp(<<>>, 0, 0,
					    F1, _) ->
    #rpbyokozunaschemagetresp{schema = F1};
dfp_read_field_def_rpbyokozunaschemagetresp(Other, Z1,
					    Z2, F1, TrUserData) ->
    dg_read_field_def_rpbyokozunaschemagetresp(Other, Z1,
					       Z2, F1, TrUserData).

dg_read_field_def_rpbyokozunaschemagetresp(<<1:1, X:7,
					     Rest/binary>>,
					   N, Acc, F1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_rpbyokozunaschemagetresp(Rest, N + 7,
					       X bsl N + Acc, F1, TrUserData);
dg_read_field_def_rpbyokozunaschemagetresp(<<0:1, X:7,
					     Rest/binary>>,
					   N, Acc, F1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_rpbyokozunaschemagetresp_schema(Rest, 0, 0, F1,
						  TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_rpbyokozunaschemagetresp(Rest, 0, 0, F1,
						     TrUserData);
	    1 ->
		skip_64_rpbyokozunaschemagetresp(Rest, 0, 0, F1,
						 TrUserData);
	    2 ->
		skip_length_delimited_rpbyokozunaschemagetresp(Rest, 0,
							       0, F1,
							       TrUserData);
	    5 ->
		skip_32_rpbyokozunaschemagetresp(Rest, 0, 0, F1,
						 TrUserData)
	  end
    end;
dg_read_field_def_rpbyokozunaschemagetresp(<<>>, 0, 0,
					   F1, _) ->
    #rpbyokozunaschemagetresp{schema = F1}.

d_field_rpbyokozunaschemagetresp_schema(<<1:1, X:7,
					  Rest/binary>>,
					N, Acc, F1, TrUserData)
    when N < 57 ->
    d_field_rpbyokozunaschemagetresp_schema(Rest, N + 7,
					    X bsl N + Acc, F1, TrUserData);
d_field_rpbyokozunaschemagetresp_schema(<<0:1, X:7,
					  Rest/binary>>,
					N, Acc, F1, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bs:Len/binary, Rest2/binary>> = Rest,
    NewFValue = id(d_msg_rpbyokozunaschema(Bs, TrUserData),
		   TrUserData),
    dfp_read_field_def_rpbyokozunaschemagetresp(Rest2, 0, 0,
						if F1 == undefined -> NewFValue;
						   true ->
						       merge_msg_rpbyokozunaschema(F1,
										   NewFValue,
										   TrUserData)
						end,
						TrUserData).


skip_varint_rpbyokozunaschemagetresp(<<1:1, _:7,
				       Rest/binary>>,
				     Z1, Z2, F1, TrUserData) ->
    skip_varint_rpbyokozunaschemagetresp(Rest, Z1, Z2, F1,
					 TrUserData);
skip_varint_rpbyokozunaschemagetresp(<<0:1, _:7,
				       Rest/binary>>,
				     Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschemagetresp(Rest, Z1,
						Z2, F1, TrUserData).


skip_length_delimited_rpbyokozunaschemagetresp(<<1:1,
						 X:7, Rest/binary>>,
					       N, Acc, F1, TrUserData)
    when N < 57 ->
    skip_length_delimited_rpbyokozunaschemagetresp(Rest,
						   N + 7, X bsl N + Acc, F1,
						   TrUserData);
skip_length_delimited_rpbyokozunaschemagetresp(<<0:1,
						 X:7, Rest/binary>>,
					       N, Acc, F1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_rpbyokozunaschemagetresp(Rest2, 0, 0,
						F1, TrUserData).


skip_32_rpbyokozunaschemagetresp(<<_:32, Rest/binary>>,
				 Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschemagetresp(Rest, Z1,
						Z2, F1, TrUserData).


skip_64_rpbyokozunaschemagetresp(<<_:64, Rest/binary>>,
				 Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaschemagetresp(Rest, Z1,
						Z2, F1, TrUserData).


d_msg_rpbyokozunaindex(Bin, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindex(Bin, 0, 0,
					id(undefined, TrUserData),
					id(undefined, TrUserData),
					id(undefined, TrUserData), TrUserData).

dfp_read_field_def_rpbyokozunaindex(<<10, Rest/binary>>,
				    Z1, Z2, F1, F2, F3, TrUserData) ->
    d_field_rpbyokozunaindex_name(Rest, Z1, Z2, F1, F2, F3,
				  TrUserData);
dfp_read_field_def_rpbyokozunaindex(<<18, Rest/binary>>,
				    Z1, Z2, F1, F2, F3, TrUserData) ->
    d_field_rpbyokozunaindex_schema(Rest, Z1, Z2, F1, F2,
				    F3, TrUserData);
dfp_read_field_def_rpbyokozunaindex(<<24, Rest/binary>>,
				    Z1, Z2, F1, F2, F3, TrUserData) ->
    d_field_rpbyokozunaindex_n_val(Rest, Z1, Z2, F1, F2, F3,
				   TrUserData);
dfp_read_field_def_rpbyokozunaindex(<<>>, 0, 0, F1, F2,
				    F3, _) ->
    #rpbyokozunaindex{name = F1, schema = F2, n_val = F3};
dfp_read_field_def_rpbyokozunaindex(Other, Z1, Z2, F1,
				    F2, F3, TrUserData) ->
    dg_read_field_def_rpbyokozunaindex(Other, Z1, Z2, F1,
				       F2, F3, TrUserData).

dg_read_field_def_rpbyokozunaindex(<<1:1, X:7,
				     Rest/binary>>,
				   N, Acc, F1, F2, F3, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_rpbyokozunaindex(Rest, N + 7,
				       X bsl N + Acc, F1, F2, F3, TrUserData);
dg_read_field_def_rpbyokozunaindex(<<0:1, X:7,
				     Rest/binary>>,
				   N, Acc, F1, F2, F3, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_rpbyokozunaindex_name(Rest, 0, 0, F1, F2, F3,
					TrUserData);
      18 ->
	  d_field_rpbyokozunaindex_schema(Rest, 0, 0, F1, F2, F3,
					  TrUserData);
      24 ->
	  d_field_rpbyokozunaindex_n_val(Rest, 0, 0, F1, F2, F3,
					 TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_rpbyokozunaindex(Rest, 0, 0, F1, F2, F3,
					     TrUserData);
	    1 ->
		skip_64_rpbyokozunaindex(Rest, 0, 0, F1, F2, F3,
					 TrUserData);
	    2 ->
		skip_length_delimited_rpbyokozunaindex(Rest, 0, 0, F1,
						       F2, F3, TrUserData);
	    5 ->
		skip_32_rpbyokozunaindex(Rest, 0, 0, F1, F2, F3,
					 TrUserData)
	  end
    end;
dg_read_field_def_rpbyokozunaindex(<<>>, 0, 0, F1, F2,
				   F3, _) ->
    #rpbyokozunaindex{name = F1, schema = F2, n_val = F3}.

d_field_rpbyokozunaindex_name(<<1:1, X:7, Rest/binary>>,
			      N, Acc, F1, F2, F3, TrUserData)
    when N < 57 ->
    d_field_rpbyokozunaindex_name(Rest, N + 7,
				  X bsl N + Acc, F1, F2, F3, TrUserData);
d_field_rpbyokozunaindex_name(<<0:1, X:7, Rest/binary>>,
			      N, Acc, _, F2, F3, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_rpbyokozunaindex(Rest2, 0, 0,
					NewFValue, F2, F3, TrUserData).


d_field_rpbyokozunaindex_schema(<<1:1, X:7,
				  Rest/binary>>,
				N, Acc, F1, F2, F3, TrUserData)
    when N < 57 ->
    d_field_rpbyokozunaindex_schema(Rest, N + 7,
				    X bsl N + Acc, F1, F2, F3, TrUserData);
d_field_rpbyokozunaindex_schema(<<0:1, X:7,
				  Rest/binary>>,
				N, Acc, F1, _, F3, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_rpbyokozunaindex(Rest2, 0, 0, F1,
					NewFValue, F3, TrUserData).


d_field_rpbyokozunaindex_n_val(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F1, F2, F3, TrUserData)
    when N < 57 ->
    d_field_rpbyokozunaindex_n_val(Rest, N + 7,
				   X bsl N + Acc, F1, F2, F3, TrUserData);
d_field_rpbyokozunaindex_n_val(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F1, F2, _, TrUserData) ->
    NewFValue = X bsl N + Acc,
    dfp_read_field_def_rpbyokozunaindex(Rest, 0, 0, F1, F2,
					NewFValue, TrUserData).


skip_varint_rpbyokozunaindex(<<1:1, _:7, Rest/binary>>,
			     Z1, Z2, F1, F2, F3, TrUserData) ->
    skip_varint_rpbyokozunaindex(Rest, Z1, Z2, F1, F2, F3,
				 TrUserData);
skip_varint_rpbyokozunaindex(<<0:1, _:7, Rest/binary>>,
			     Z1, Z2, F1, F2, F3, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindex(Rest, Z1, Z2, F1,
					F2, F3, TrUserData).


skip_length_delimited_rpbyokozunaindex(<<1:1, X:7,
					 Rest/binary>>,
				       N, Acc, F1, F2, F3, TrUserData)
    when N < 57 ->
    skip_length_delimited_rpbyokozunaindex(Rest, N + 7,
					   X bsl N + Acc, F1, F2, F3,
					   TrUserData);
skip_length_delimited_rpbyokozunaindex(<<0:1, X:7,
					 Rest/binary>>,
				       N, Acc, F1, F2, F3, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_rpbyokozunaindex(Rest2, 0, 0, F1, F2,
					F3, TrUserData).


skip_32_rpbyokozunaindex(<<_:32, Rest/binary>>, Z1, Z2,
			 F1, F2, F3, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindex(Rest, Z1, Z2, F1,
					F2, F3, TrUserData).


skip_64_rpbyokozunaindex(<<_:64, Rest/binary>>, Z1, Z2,
			 F1, F2, F3, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindex(Rest, Z1, Z2, F1,
					F2, F3, TrUserData).


d_msg_rpbyokozunaindexputreq(Bin, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexputreq(Bin, 0, 0,
					      id(undefined, TrUserData),
					      id(undefined, TrUserData),
					      TrUserData).

dfp_read_field_def_rpbyokozunaindexputreq(<<10,
					    Rest/binary>>,
					  Z1, Z2, F1, F2, TrUserData) ->
    d_field_rpbyokozunaindexputreq_index(Rest, Z1, Z2, F1,
					 F2, TrUserData);
dfp_read_field_def_rpbyokozunaindexputreq(<<16,
					    Rest/binary>>,
					  Z1, Z2, F1, F2, TrUserData) ->
    d_field_rpbyokozunaindexputreq_timeout(Rest, Z1, Z2, F1,
					   F2, TrUserData);
dfp_read_field_def_rpbyokozunaindexputreq(<<>>, 0, 0,
					  F1, F2, _) ->
    #rpbyokozunaindexputreq{index = F1, timeout = F2};
dfp_read_field_def_rpbyokozunaindexputreq(Other, Z1, Z2,
					  F1, F2, TrUserData) ->
    dg_read_field_def_rpbyokozunaindexputreq(Other, Z1, Z2,
					     F1, F2, TrUserData).

dg_read_field_def_rpbyokozunaindexputreq(<<1:1, X:7,
					   Rest/binary>>,
					 N, Acc, F1, F2, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_rpbyokozunaindexputreq(Rest, N + 7,
					     X bsl N + Acc, F1, F2, TrUserData);
dg_read_field_def_rpbyokozunaindexputreq(<<0:1, X:7,
					   Rest/binary>>,
					 N, Acc, F1, F2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_rpbyokozunaindexputreq_index(Rest, 0, 0, F1, F2,
					       TrUserData);
      16 ->
	  d_field_rpbyokozunaindexputreq_timeout(Rest, 0, 0, F1,
						 F2, TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_rpbyokozunaindexputreq(Rest, 0, 0, F1, F2,
						   TrUserData);
	    1 ->
		skip_64_rpbyokozunaindexputreq(Rest, 0, 0, F1, F2,
					       TrUserData);
	    2 ->
		skip_length_delimited_rpbyokozunaindexputreq(Rest, 0, 0,
							     F1, F2,
							     TrUserData);
	    5 ->
		skip_32_rpbyokozunaindexputreq(Rest, 0, 0, F1, F2,
					       TrUserData)
	  end
    end;
dg_read_field_def_rpbyokozunaindexputreq(<<>>, 0, 0, F1,
					 F2, _) ->
    #rpbyokozunaindexputreq{index = F1, timeout = F2}.

d_field_rpbyokozunaindexputreq_index(<<1:1, X:7,
				       Rest/binary>>,
				     N, Acc, F1, F2, TrUserData)
    when N < 57 ->
    d_field_rpbyokozunaindexputreq_index(Rest, N + 7,
					 X bsl N + Acc, F1, F2, TrUserData);
d_field_rpbyokozunaindexputreq_index(<<0:1, X:7,
				       Rest/binary>>,
				     N, Acc, F1, F2, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bs:Len/binary, Rest2/binary>> = Rest,
    NewFValue = id(d_msg_rpbyokozunaindex(Bs, TrUserData),
		   TrUserData),
    dfp_read_field_def_rpbyokozunaindexputreq(Rest2, 0, 0,
					      if F1 == undefined -> NewFValue;
						 true ->
						     merge_msg_rpbyokozunaindex(F1,
										NewFValue,
										TrUserData)
					      end,
					      F2, TrUserData).


d_field_rpbyokozunaindexputreq_timeout(<<1:1, X:7,
					 Rest/binary>>,
				       N, Acc, F1, F2, TrUserData)
    when N < 57 ->
    d_field_rpbyokozunaindexputreq_timeout(Rest, N + 7,
					   X bsl N + Acc, F1, F2, TrUserData);
d_field_rpbyokozunaindexputreq_timeout(<<0:1, X:7,
					 Rest/binary>>,
				       N, Acc, F1, _, TrUserData) ->
    NewFValue = X bsl N + Acc,
    dfp_read_field_def_rpbyokozunaindexputreq(Rest, 0, 0,
					      F1, NewFValue, TrUserData).


skip_varint_rpbyokozunaindexputreq(<<1:1, _:7,
				     Rest/binary>>,
				   Z1, Z2, F1, F2, TrUserData) ->
    skip_varint_rpbyokozunaindexputreq(Rest, Z1, Z2, F1, F2,
				       TrUserData);
skip_varint_rpbyokozunaindexputreq(<<0:1, _:7,
				     Rest/binary>>,
				   Z1, Z2, F1, F2, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexputreq(Rest, Z1, Z2,
					      F1, F2, TrUserData).


skip_length_delimited_rpbyokozunaindexputreq(<<1:1, X:7,
					       Rest/binary>>,
					     N, Acc, F1, F2, TrUserData)
    when N < 57 ->
    skip_length_delimited_rpbyokozunaindexputreq(Rest,
						 N + 7, X bsl N + Acc, F1, F2,
						 TrUserData);
skip_length_delimited_rpbyokozunaindexputreq(<<0:1, X:7,
					       Rest/binary>>,
					     N, Acc, F1, F2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_rpbyokozunaindexputreq(Rest2, 0, 0,
					      F1, F2, TrUserData).


skip_32_rpbyokozunaindexputreq(<<_:32, Rest/binary>>,
			       Z1, Z2, F1, F2, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexputreq(Rest, Z1, Z2,
					      F1, F2, TrUserData).


skip_64_rpbyokozunaindexputreq(<<_:64, Rest/binary>>,
			       Z1, Z2, F1, F2, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexputreq(Rest, Z1, Z2,
					      F1, F2, TrUserData).


d_msg_rpbyokozunaindexgetreq(Bin, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexgetreq(Bin, 0, 0,
					      id(undefined, TrUserData),
					      TrUserData).

dfp_read_field_def_rpbyokozunaindexgetreq(<<10,
					    Rest/binary>>,
					  Z1, Z2, F1, TrUserData) ->
    d_field_rpbyokozunaindexgetreq_name(Rest, Z1, Z2, F1,
					TrUserData);
dfp_read_field_def_rpbyokozunaindexgetreq(<<>>, 0, 0,
					  F1, _) ->
    #rpbyokozunaindexgetreq{name = F1};
dfp_read_field_def_rpbyokozunaindexgetreq(Other, Z1, Z2,
					  F1, TrUserData) ->
    dg_read_field_def_rpbyokozunaindexgetreq(Other, Z1, Z2,
					     F1, TrUserData).

dg_read_field_def_rpbyokozunaindexgetreq(<<1:1, X:7,
					   Rest/binary>>,
					 N, Acc, F1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_rpbyokozunaindexgetreq(Rest, N + 7,
					     X bsl N + Acc, F1, TrUserData);
dg_read_field_def_rpbyokozunaindexgetreq(<<0:1, X:7,
					   Rest/binary>>,
					 N, Acc, F1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_rpbyokozunaindexgetreq_name(Rest, 0, 0, F1,
					      TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_rpbyokozunaindexgetreq(Rest, 0, 0, F1,
						   TrUserData);
	    1 ->
		skip_64_rpbyokozunaindexgetreq(Rest, 0, 0, F1,
					       TrUserData);
	    2 ->
		skip_length_delimited_rpbyokozunaindexgetreq(Rest, 0, 0,
							     F1, TrUserData);
	    5 ->
		skip_32_rpbyokozunaindexgetreq(Rest, 0, 0, F1,
					       TrUserData)
	  end
    end;
dg_read_field_def_rpbyokozunaindexgetreq(<<>>, 0, 0, F1,
					 _) ->
    #rpbyokozunaindexgetreq{name = F1}.

d_field_rpbyokozunaindexgetreq_name(<<1:1, X:7,
				      Rest/binary>>,
				    N, Acc, F1, TrUserData)
    when N < 57 ->
    d_field_rpbyokozunaindexgetreq_name(Rest, N + 7,
					X bsl N + Acc, F1, TrUserData);
d_field_rpbyokozunaindexgetreq_name(<<0:1, X:7,
				      Rest/binary>>,
				    N, Acc, _, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_rpbyokozunaindexgetreq(Rest2, 0, 0,
					      NewFValue, TrUserData).


skip_varint_rpbyokozunaindexgetreq(<<1:1, _:7,
				     Rest/binary>>,
				   Z1, Z2, F1, TrUserData) ->
    skip_varint_rpbyokozunaindexgetreq(Rest, Z1, Z2, F1,
				       TrUserData);
skip_varint_rpbyokozunaindexgetreq(<<0:1, _:7,
				     Rest/binary>>,
				   Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexgetreq(Rest, Z1, Z2,
					      F1, TrUserData).


skip_length_delimited_rpbyokozunaindexgetreq(<<1:1, X:7,
					       Rest/binary>>,
					     N, Acc, F1, TrUserData)
    when N < 57 ->
    skip_length_delimited_rpbyokozunaindexgetreq(Rest,
						 N + 7, X bsl N + Acc, F1,
						 TrUserData);
skip_length_delimited_rpbyokozunaindexgetreq(<<0:1, X:7,
					       Rest/binary>>,
					     N, Acc, F1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_rpbyokozunaindexgetreq(Rest2, 0, 0,
					      F1, TrUserData).


skip_32_rpbyokozunaindexgetreq(<<_:32, Rest/binary>>,
			       Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexgetreq(Rest, Z1, Z2,
					      F1, TrUserData).


skip_64_rpbyokozunaindexgetreq(<<_:64, Rest/binary>>,
			       Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexgetreq(Rest, Z1, Z2,
					      F1, TrUserData).


d_msg_rpbyokozunaindexdeletereq(Bin, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexdeletereq(Bin, 0, 0,
						 id(undefined, TrUserData),
						 TrUserData).

dfp_read_field_def_rpbyokozunaindexdeletereq(<<10,
					       Rest/binary>>,
					     Z1, Z2, F1, TrUserData) ->
    d_field_rpbyokozunaindexdeletereq_name(Rest, Z1, Z2, F1,
					   TrUserData);
dfp_read_field_def_rpbyokozunaindexdeletereq(<<>>, 0, 0,
					     F1, _) ->
    #rpbyokozunaindexdeletereq{name = F1};
dfp_read_field_def_rpbyokozunaindexdeletereq(Other, Z1,
					     Z2, F1, TrUserData) ->
    dg_read_field_def_rpbyokozunaindexdeletereq(Other, Z1,
						Z2, F1, TrUserData).

dg_read_field_def_rpbyokozunaindexdeletereq(<<1:1, X:7,
					      Rest/binary>>,
					    N, Acc, F1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_rpbyokozunaindexdeletereq(Rest, N + 7,
						X bsl N + Acc, F1, TrUserData);
dg_read_field_def_rpbyokozunaindexdeletereq(<<0:1, X:7,
					      Rest/binary>>,
					    N, Acc, F1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_rpbyokozunaindexdeletereq_name(Rest, 0, 0, F1,
						 TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_rpbyokozunaindexdeletereq(Rest, 0, 0, F1,
						      TrUserData);
	    1 ->
		skip_64_rpbyokozunaindexdeletereq(Rest, 0, 0, F1,
						  TrUserData);
	    2 ->
		skip_length_delimited_rpbyokozunaindexdeletereq(Rest, 0,
								0, F1,
								TrUserData);
	    5 ->
		skip_32_rpbyokozunaindexdeletereq(Rest, 0, 0, F1,
						  TrUserData)
	  end
    end;
dg_read_field_def_rpbyokozunaindexdeletereq(<<>>, 0, 0,
					    F1, _) ->
    #rpbyokozunaindexdeletereq{name = F1}.

d_field_rpbyokozunaindexdeletereq_name(<<1:1, X:7,
					 Rest/binary>>,
				       N, Acc, F1, TrUserData)
    when N < 57 ->
    d_field_rpbyokozunaindexdeletereq_name(Rest, N + 7,
					   X bsl N + Acc, F1, TrUserData);
d_field_rpbyokozunaindexdeletereq_name(<<0:1, X:7,
					 Rest/binary>>,
				       N, Acc, _, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_rpbyokozunaindexdeletereq(Rest2, 0,
						 0, NewFValue, TrUserData).


skip_varint_rpbyokozunaindexdeletereq(<<1:1, _:7,
					Rest/binary>>,
				      Z1, Z2, F1, TrUserData) ->
    skip_varint_rpbyokozunaindexdeletereq(Rest, Z1, Z2, F1,
					  TrUserData);
skip_varint_rpbyokozunaindexdeletereq(<<0:1, _:7,
					Rest/binary>>,
				      Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexdeletereq(Rest, Z1,
						 Z2, F1, TrUserData).


skip_length_delimited_rpbyokozunaindexdeletereq(<<1:1,
						  X:7, Rest/binary>>,
						N, Acc, F1, TrUserData)
    when N < 57 ->
    skip_length_delimited_rpbyokozunaindexdeletereq(Rest,
						    N + 7, X bsl N + Acc, F1,
						    TrUserData);
skip_length_delimited_rpbyokozunaindexdeletereq(<<0:1,
						  X:7, Rest/binary>>,
						N, Acc, F1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_rpbyokozunaindexdeletereq(Rest2, 0,
						 0, F1, TrUserData).


skip_32_rpbyokozunaindexdeletereq(<<_:32, Rest/binary>>,
				  Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexdeletereq(Rest, Z1,
						 Z2, F1, TrUserData).


skip_64_rpbyokozunaindexdeletereq(<<_:64, Rest/binary>>,
				  Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexdeletereq(Rest, Z1,
						 Z2, F1, TrUserData).


d_msg_rpbyokozunaindexgetresp(Bin, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexgetresp(Bin, 0, 0,
					       id([], TrUserData), TrUserData).

dfp_read_field_def_rpbyokozunaindexgetresp(<<10,
					     Rest/binary>>,
					   Z1, Z2, F1, TrUserData) ->
    d_field_rpbyokozunaindexgetresp_index(Rest, Z1, Z2, F1,
					  TrUserData);
dfp_read_field_def_rpbyokozunaindexgetresp(<<>>, 0, 0,
					   F1, TrUserData) ->
    #rpbyokozunaindexgetresp{index =
				 lists_reverse(F1, TrUserData)};
dfp_read_field_def_rpbyokozunaindexgetresp(Other, Z1,
					   Z2, F1, TrUserData) ->
    dg_read_field_def_rpbyokozunaindexgetresp(Other, Z1, Z2,
					      F1, TrUserData).

dg_read_field_def_rpbyokozunaindexgetresp(<<1:1, X:7,
					    Rest/binary>>,
					  N, Acc, F1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_rpbyokozunaindexgetresp(Rest, N + 7,
					      X bsl N + Acc, F1, TrUserData);
dg_read_field_def_rpbyokozunaindexgetresp(<<0:1, X:7,
					    Rest/binary>>,
					  N, Acc, F1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_rpbyokozunaindexgetresp_index(Rest, 0, 0, F1,
						TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_rpbyokozunaindexgetresp(Rest, 0, 0, F1,
						    TrUserData);
	    1 ->
		skip_64_rpbyokozunaindexgetresp(Rest, 0, 0, F1,
						TrUserData);
	    2 ->
		skip_length_delimited_rpbyokozunaindexgetresp(Rest, 0,
							      0, F1,
							      TrUserData);
	    5 ->
		skip_32_rpbyokozunaindexgetresp(Rest, 0, 0, F1,
						TrUserData)
	  end
    end;
dg_read_field_def_rpbyokozunaindexgetresp(<<>>, 0, 0,
					  F1, TrUserData) ->
    #rpbyokozunaindexgetresp{index =
				 lists_reverse(F1, TrUserData)}.

d_field_rpbyokozunaindexgetresp_index(<<1:1, X:7,
					Rest/binary>>,
				      N, Acc, F1, TrUserData)
    when N < 57 ->
    d_field_rpbyokozunaindexgetresp_index(Rest, N + 7,
					  X bsl N + Acc, F1, TrUserData);
d_field_rpbyokozunaindexgetresp_index(<<0:1, X:7,
					Rest/binary>>,
				      N, Acc, F1, TrUserData) ->
    Len = X bsl N + Acc,
    <<Bs:Len/binary, Rest2/binary>> = Rest,
    NewFValue = id(d_msg_rpbyokozunaindex(Bs, TrUserData),
		   TrUserData),
    dfp_read_field_def_rpbyokozunaindexgetresp(Rest2, 0, 0,
					       cons(NewFValue, F1, TrUserData),
					       TrUserData).


skip_varint_rpbyokozunaindexgetresp(<<1:1, _:7,
				      Rest/binary>>,
				    Z1, Z2, F1, TrUserData) ->
    skip_varint_rpbyokozunaindexgetresp(Rest, Z1, Z2, F1,
					TrUserData);
skip_varint_rpbyokozunaindexgetresp(<<0:1, _:7,
				      Rest/binary>>,
				    Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexgetresp(Rest, Z1, Z2,
					       F1, TrUserData).


skip_length_delimited_rpbyokozunaindexgetresp(<<1:1,
						X:7, Rest/binary>>,
					      N, Acc, F1, TrUserData)
    when N < 57 ->
    skip_length_delimited_rpbyokozunaindexgetresp(Rest,
						  N + 7, X bsl N + Acc, F1,
						  TrUserData);
skip_length_delimited_rpbyokozunaindexgetresp(<<0:1,
						X:7, Rest/binary>>,
					      N, Acc, F1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_rpbyokozunaindexgetresp(Rest2, 0, 0,
					       F1, TrUserData).


skip_32_rpbyokozunaindexgetresp(<<_:32, Rest/binary>>,
				Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexgetresp(Rest, Z1, Z2,
					       F1, TrUserData).


skip_64_rpbyokozunaindexgetresp(<<_:64, Rest/binary>>,
				Z1, Z2, F1, TrUserData) ->
    dfp_read_field_def_rpbyokozunaindexgetresp(Rest, Z1, Z2,
					       F1, TrUserData).






merge_msgs(Prev, New) -> merge_msgs(Prev, New, []).

merge_msgs(Prev, New, Opts)
    when element(1, Prev) =:= element(1, New) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case Prev of
      #rpbyokozunaschemagetreq{} ->
	  merge_msg_rpbyokozunaschemagetreq(Prev, New,
					    TrUserData);
      #rpbyokozunaschema{} ->
	  merge_msg_rpbyokozunaschema(Prev, New, TrUserData);
      #rpbyokozunaschemaputreq{} ->
	  merge_msg_rpbyokozunaschemaputreq(Prev, New,
					    TrUserData);
      #rpbyokozunaschemagetresp{} ->
	  merge_msg_rpbyokozunaschemagetresp(Prev, New,
					     TrUserData);
      #rpbyokozunaindex{} ->
	  merge_msg_rpbyokozunaindex(Prev, New, TrUserData);
      #rpbyokozunaindexputreq{} ->
	  merge_msg_rpbyokozunaindexputreq(Prev, New, TrUserData);
      #rpbyokozunaindexgetreq{} ->
	  merge_msg_rpbyokozunaindexgetreq(Prev, New, TrUserData);
      #rpbyokozunaindexdeletereq{} ->
	  merge_msg_rpbyokozunaindexdeletereq(Prev, New,
					      TrUserData);
      #rpbyokozunaindexgetresp{} ->
	  merge_msg_rpbyokozunaindexgetresp(Prev, New, TrUserData)
    end.

merge_msg_rpbyokozunaschemagetreq(#rpbyokozunaschemagetreq{},
				  #rpbyokozunaschemagetreq{name = NFname}, _) ->
    #rpbyokozunaschemagetreq{name = NFname}.

merge_msg_rpbyokozunaschema(#rpbyokozunaschema{content =
						   PFcontent},
			    #rpbyokozunaschema{name = NFname,
					       content = NFcontent},
			    _) ->
    #rpbyokozunaschema{name = NFname,
		       content =
			   if NFcontent =:= undefined -> PFcontent;
			      true -> NFcontent
			   end}.

merge_msg_rpbyokozunaschemaputreq(#rpbyokozunaschemaputreq{schema
							       = PFschema},
				  #rpbyokozunaschemaputreq{schema = NFschema},
				  TrUserData) ->
    #rpbyokozunaschemaputreq{schema =
				 if PFschema /= undefined,
				    NFschema /= undefined ->
					merge_msg_rpbyokozunaschema(PFschema,
								    NFschema,
								    TrUserData);
				    PFschema == undefined -> NFschema;
				    NFschema == undefined -> PFschema
				 end}.

merge_msg_rpbyokozunaschemagetresp(#rpbyokozunaschemagetresp{schema
								 = PFschema},
				   #rpbyokozunaschemagetresp{schema = NFschema},
				   TrUserData) ->
    #rpbyokozunaschemagetresp{schema =
				  if PFschema /= undefined,
				     NFschema /= undefined ->
					 merge_msg_rpbyokozunaschema(PFschema,
								     NFschema,
								     TrUserData);
				     PFschema == undefined -> NFschema;
				     NFschema == undefined -> PFschema
				  end}.

merge_msg_rpbyokozunaindex(#rpbyokozunaindex{schema =
						 PFschema,
					     n_val = PFn_val},
			   #rpbyokozunaindex{name = NFname, schema = NFschema,
					     n_val = NFn_val},
			   _) ->
    #rpbyokozunaindex{name = NFname,
		      schema =
			  if NFschema =:= undefined -> PFschema;
			     true -> NFschema
			  end,
		      n_val =
			  if NFn_val =:= undefined -> PFn_val;
			     true -> NFn_val
			  end}.

merge_msg_rpbyokozunaindexputreq(#rpbyokozunaindexputreq{index
							     = PFindex,
							 timeout = PFtimeout},
				 #rpbyokozunaindexputreq{index = NFindex,
							 timeout = NFtimeout},
				 TrUserData) ->
    #rpbyokozunaindexputreq{index =
				if PFindex /= undefined, NFindex /= undefined ->
				       merge_msg_rpbyokozunaindex(PFindex,
								  NFindex,
								  TrUserData);
				   PFindex == undefined -> NFindex;
				   NFindex == undefined -> PFindex
				end,
			    timeout =
				if NFtimeout =:= undefined -> PFtimeout;
				   true -> NFtimeout
				end}.

merge_msg_rpbyokozunaindexgetreq(#rpbyokozunaindexgetreq{name
							     = PFname},
				 #rpbyokozunaindexgetreq{name = NFname}, _) ->
    #rpbyokozunaindexgetreq{name =
				if NFname =:= undefined -> PFname;
				   true -> NFname
				end}.

merge_msg_rpbyokozunaindexdeletereq(#rpbyokozunaindexdeletereq{},
				    #rpbyokozunaindexdeletereq{name = NFname},
				    _) ->
    #rpbyokozunaindexdeletereq{name = NFname}.

merge_msg_rpbyokozunaindexgetresp(#rpbyokozunaindexgetresp{index
							       = PFindex},
				  #rpbyokozunaindexgetresp{index = NFindex},
				  TrUserData) ->
    #rpbyokozunaindexgetresp{index =
				 'erlang_++'(PFindex, NFindex, TrUserData)}.



verify_msg(Msg) -> verify_msg(Msg, []).

verify_msg(Msg, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case Msg of
      #rpbyokozunaschemagetreq{} ->
	  v_msg_rpbyokozunaschemagetreq(Msg,
					[rpbyokozunaschemagetreq], TrUserData);
      #rpbyokozunaschema{} ->
	  v_msg_rpbyokozunaschema(Msg, [rpbyokozunaschema],
				  TrUserData);
      #rpbyokozunaschemaputreq{} ->
	  v_msg_rpbyokozunaschemaputreq(Msg,
					[rpbyokozunaschemaputreq], TrUserData);
      #rpbyokozunaschemagetresp{} ->
	  v_msg_rpbyokozunaschemagetresp(Msg,
					 [rpbyokozunaschemagetresp],
					 TrUserData);
      #rpbyokozunaindex{} ->
	  v_msg_rpbyokozunaindex(Msg, [rpbyokozunaindex],
				 TrUserData);
      #rpbyokozunaindexputreq{} ->
	  v_msg_rpbyokozunaindexputreq(Msg,
				       [rpbyokozunaindexputreq], TrUserData);
      #rpbyokozunaindexgetreq{} ->
	  v_msg_rpbyokozunaindexgetreq(Msg,
				       [rpbyokozunaindexgetreq], TrUserData);
      #rpbyokozunaindexdeletereq{} ->
	  v_msg_rpbyokozunaindexdeletereq(Msg,
					  [rpbyokozunaindexdeletereq],
					  TrUserData);
      #rpbyokozunaindexgetresp{} ->
	  v_msg_rpbyokozunaindexgetresp(Msg,
					[rpbyokozunaindexgetresp], TrUserData);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


v_msg_rpbyokozunaschemagetreq(#rpbyokozunaschemagetreq{name
							   = F1},
			      Path, _) ->
    v_type_bytes(F1, [name | Path]), ok.

v_msg_rpbyokozunaschema(#rpbyokozunaschema{name = F1,
					   content = F2},
			Path, _) ->
    v_type_bytes(F1, [name | Path]),
    if F2 == undefined -> ok;
       true -> v_type_bytes(F2, [content | Path])
    end,
    ok;
v_msg_rpbyokozunaschema(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, rpbyokozunaschema}, X,
		  Path).

v_msg_rpbyokozunaschemaputreq(#rpbyokozunaschemaputreq{schema
							   = F1},
			      Path, TrUserData) ->
    v_msg_rpbyokozunaschema(F1, [schema | Path],
			    TrUserData),
    ok.

v_msg_rpbyokozunaschemagetresp(#rpbyokozunaschemagetresp{schema
							     = F1},
			       Path, TrUserData) ->
    v_msg_rpbyokozunaschema(F1, [schema | Path],
			    TrUserData),
    ok.

v_msg_rpbyokozunaindex(#rpbyokozunaindex{name = F1,
					 schema = F2, n_val = F3},
		       Path, _) ->
    v_type_bytes(F1, [name | Path]),
    if F2 == undefined -> ok;
       true -> v_type_bytes(F2, [schema | Path])
    end,
    if F3 == undefined -> ok;
       true -> v_type_uint32(F3, [n_val | Path])
    end,
    ok;
v_msg_rpbyokozunaindex(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, rpbyokozunaindex}, X,
		  Path).

v_msg_rpbyokozunaindexputreq(#rpbyokozunaindexputreq{index
							 = F1,
						     timeout = F2},
			     Path, TrUserData) ->
    v_msg_rpbyokozunaindex(F1, [index | Path], TrUserData),
    if F2 == undefined -> ok;
       true -> v_type_uint32(F2, [timeout | Path])
    end,
    ok.

v_msg_rpbyokozunaindexgetreq(#rpbyokozunaindexgetreq{name
							 = F1},
			     Path, _) ->
    if F1 == undefined -> ok;
       true -> v_type_bytes(F1, [name | Path])
    end,
    ok.

v_msg_rpbyokozunaindexdeletereq(#rpbyokozunaindexdeletereq{name
							       = F1},
				Path, _) ->
    v_type_bytes(F1, [name | Path]), ok.

v_msg_rpbyokozunaindexgetresp(#rpbyokozunaindexgetresp{index
							   = F1},
			      Path, TrUserData) ->
    if is_list(F1) ->
	   _ = [v_msg_rpbyokozunaindex(Elem, [index | Path],
				       TrUserData)
		|| Elem <- F1],
	   ok;
       true ->
	   mk_type_error({invalid_list_of,
			  {msg, rpbyokozunaindex}},
			 F1, Path)
    end,
    ok.

v_type_uint32(N, _Path) when 0 =< N, N =< 4294967295 ->
    ok;
v_type_uint32(N, Path) when is_integer(N) ->
    mk_type_error({value_out_of_range, uint32, unsigned,
		   32},
		  N, Path);
v_type_uint32(X, Path) ->
    mk_type_error({bad_integer, uint32, unsigned, 32}, X,
		  Path).

v_type_bytes(B, _Path) when is_binary(B) -> ok;
v_type_bytes(B, _Path) when is_list(B) -> ok;
v_type_bytes(X, Path) ->
    mk_type_error(bad_binary_value, X, Path).

-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error,
		  {Error, [{value, ValueSeen}, {path, Path2}]}}).


prettify_path([]) -> top_level;
prettify_path(PathR) ->
    list_to_atom(string:join(lists:map(fun atom_to_list/1,
				       lists:reverse(PathR)),
			     ".")).



-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.



get_msg_defs() ->
    [{{msg, rpbyokozunaschemagetreq},
      [[{name, name}, {fnum, 1}, {rnum, 2}, {type, bytes},
	{occurrence, required}, {opts, []}]]},
     {{msg, rpbyokozunaschema},
      [[{name, name}, {fnum, 1}, {rnum, 2}, {type, bytes},
	{occurrence, required}, {opts, []}],
       [{name, content}, {fnum, 2}, {rnum, 3}, {type, bytes},
	{occurrence, optional}, {opts, []}]]},
     {{msg, rpbyokozunaschemaputreq},
      [[{name, schema}, {fnum, 1}, {rnum, 2},
	{type, {msg, rpbyokozunaschema}},
	{occurrence, required}, {opts, []}]]},
     {{msg, rpbyokozunaschemagetresp},
      [[{name, schema}, {fnum, 1}, {rnum, 2},
	{type, {msg, rpbyokozunaschema}},
	{occurrence, required}, {opts, []}]]},
     {{msg, rpbyokozunaindex},
      [[{name, name}, {fnum, 1}, {rnum, 2}, {type, bytes},
	{occurrence, required}, {opts, []}],
       [{name, schema}, {fnum, 2}, {rnum, 3}, {type, bytes},
	{occurrence, optional}, {opts, []}],
       [{name, n_val}, {fnum, 3}, {rnum, 4}, {type, uint32},
	{occurrence, optional}, {opts, []}]]},
     {{msg, rpbyokozunaindexputreq},
      [[{name, index}, {fnum, 1}, {rnum, 2},
	{type, {msg, rpbyokozunaindex}}, {occurrence, required},
	{opts, []}],
       [{name, timeout}, {fnum, 2}, {rnum, 3}, {type, uint32},
	{occurrence, optional}, {opts, []}]]},
     {{msg, rpbyokozunaindexgetreq},
      [[{name, name}, {fnum, 1}, {rnum, 2}, {type, bytes},
	{occurrence, optional}, {opts, []}]]},
     {{msg, rpbyokozunaindexdeletereq},
      [[{name, name}, {fnum, 1}, {rnum, 2}, {type, bytes},
	{occurrence, required}, {opts, []}]]},
     {{msg, rpbyokozunaindexgetresp},
      [[{name, index}, {fnum, 1}, {rnum, 2},
	{type, {msg, rpbyokozunaindex}}, {occurrence, repeated},
	{opts, []}]]}].


get_msg_names() ->
    [rpbyokozunaschemagetreq, rpbyokozunaschema,
     rpbyokozunaschemaputreq, rpbyokozunaschemagetresp,
     rpbyokozunaindex, rpbyokozunaindexputreq,
     rpbyokozunaindexgetreq, rpbyokozunaindexdeletereq,
     rpbyokozunaindexgetresp].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) ->
    erlang:error({no_such_enum, EnumName}).


find_msg_def(rpbyokozunaschemagetreq) ->
    [[{name, name}, {fnum, 1}, {rnum, 2}, {type, bytes},
      {occurrence, required}, {opts, []}]];
find_msg_def(rpbyokozunaschema) ->
    [[{name, name}, {fnum, 1}, {rnum, 2}, {type, bytes},
      {occurrence, required}, {opts, []}],
     [{name, content}, {fnum, 2}, {rnum, 3}, {type, bytes},
      {occurrence, optional}, {opts, []}]];
find_msg_def(rpbyokozunaschemaputreq) ->
    [[{name, schema}, {fnum, 1}, {rnum, 2},
      {type, {msg, rpbyokozunaschema}},
      {occurrence, required}, {opts, []}]];
find_msg_def(rpbyokozunaschemagetresp) ->
    [[{name, schema}, {fnum, 1}, {rnum, 2},
      {type, {msg, rpbyokozunaschema}},
      {occurrence, required}, {opts, []}]];
find_msg_def(rpbyokozunaindex) ->
    [[{name, name}, {fnum, 1}, {rnum, 2}, {type, bytes},
      {occurrence, required}, {opts, []}],
     [{name, schema}, {fnum, 2}, {rnum, 3}, {type, bytes},
      {occurrence, optional}, {opts, []}],
     [{name, n_val}, {fnum, 3}, {rnum, 4}, {type, uint32},
      {occurrence, optional}, {opts, []}]];
find_msg_def(rpbyokozunaindexputreq) ->
    [[{name, index}, {fnum, 1}, {rnum, 2},
      {type, {msg, rpbyokozunaindex}}, {occurrence, required},
      {opts, []}],
     [{name, timeout}, {fnum, 2}, {rnum, 3}, {type, uint32},
      {occurrence, optional}, {opts, []}]];
find_msg_def(rpbyokozunaindexgetreq) ->
    [[{name, name}, {fnum, 1}, {rnum, 2}, {type, bytes},
      {occurrence, optional}, {opts, []}]];
find_msg_def(rpbyokozunaindexdeletereq) ->
    [[{name, name}, {fnum, 1}, {rnum, 2}, {type, bytes},
      {occurrence, required}, {opts, []}]];
find_msg_def(rpbyokozunaindexgetresp) ->
    [[{name, index}, {fnum, 1}, {rnum, 2},
      {type, {msg, rpbyokozunaindex}}, {occurrence, repeated},
      {opts, []}]];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) ->
    erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) ->
    erlang:error({no_enum_defs, E, V}).



get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) ->
    erlang:error({no_such_rpc, ServiceName, RpcName}).


get_package_name() -> undefined.



gpb_version_as_string() ->
    "3.26.4".

gpb_version_as_list() ->
    [3,26,4].
